version: '3'

services:
  api:
    image: "node-api"
    build: ./api
    command: npm start
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./api:/usr/api
    links:
      - mongodb
    depends_on:
      - mongodb
  
  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db