version: "3"

services:
  api:
    image: "node-api"
    build: ./api
    container_name: "API"
    command: npm start
    restart: always
    ports:
      - "3050:3050"
    volumes:
      - ./api:/usr/api
    links:
      - mongodb
    depends_on:
      - mongodb

  front:
    image: "api-front"
    build: ./front
    container_name: "React"
    command: yarn start
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./front:/usr/app
    links:
      - api
    depends_on:
      - api

  mongodb:
    image: mongo:latest
    container_name: "MongoDB"
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
